language: node_js
node_js:
  - "7"
sudo: false
cache:
  directories:
    - "node_modules"
script:
  - npm run lint
  - npm run test
  - npm run typings
  - npm run build
after_success:
  - npm run coverage